### ISSUE TITLE
Is this training code appliable to data with only person IDs and no camera IDs and timestamps?

### ISSUE THREAD

**Issue by young169** [nixingyang/FlipReID#2]
Firstly, thank you for your releasing, however, when I run 'python3 -u solution.py --dataset_name "Market1501" --use_horizontal_flipping_inside_model --nouse_horizontal_flipping_in_evaluation --steps_per_epoch 200 --epoch_num 200', an error occured. I modified the data_dir in line 38 of solution.py. What else changes should be made?
###
assert len(image_file_path_list) == 12936
AssertionError
###

**Comment by nixingyang** [comment]
Hi,
Thank you for your interest in our work.
The assertion error occurs because you do not have the expected dataset on disk. I presume that you want to conduct experiments on a different dataset.
You could implement a separate script which loads your dataset, e.g., [market1501](https://github.com/nixingyang/FlipReID/blob/master/datasets/market1501.py). By doing so, you may specify the `dataset_name` argument afterward. For each image, you have to set three attributes, namely, `image_file_path`, `identity_ID`, and `camera_ID`. You should use different values for `camera_ID`. Suppose you have `N` samples, use `{1,...,N}` as `camera_ID`.
All the best.
Xingyang Ni

**Comment by young169** [comment]
> Hi,
> Thank you for your interest in our work.
> The assertion error occurs because you do not have the expected dataset on disk. I presume that you want to conduct experiments on a different dataset.
> You could implement a separate script which loads your dataset, e.g., [market1501](https://github.com/nixingyang/FlipReID/blob/master/datasets/market1501.py). By doing so, you may specify the `dataset_name` argument afterward. For each image, you have to set three attributes, namely, `image_file_path`, `identity_ID`, and `camera_ID`. You should use different values for `camera_ID`. Suppose you have `N` samples, use `{1,...,N}` as `camera_ID`.
> All the best.
> Xingyang Ni

Thank you for your quick reply. In your suggestion : N samples use {1,...,N} as camera_ID, N represents number of training samples or training person ID? For the number of training samples could be very large as well as person ID actually.

**Comment by nixingyang** [comment]
`N` refers to the number of samples. For more details, please check [TrainDataSequence](https://github.com/nixingyang/FlipReID/blob/427d7e184c2d2b804c49b433838012aeb6b43aec/solution.py#L341).
Xingyang
